server:
  port: 8100


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  batch:
#    jdbc:
#      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
